on:
  push:
    branch:
    - main

jobs:
  build:
    name: build-apps
    runs-on: ubuntu-latest
    steps:
      - name: menampilkan teks
        run: echo "ini step build"
  testing:
    name: test-apps
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: menampilkan teks
        run: echo "ini step test"
  deployment:
    name: deployment-apps
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: menampilkan teks
        run: echo "ini step deployment"
