on:
  push:
    branch:
    - main

jobs:
  build:
    name: build-apps
    runs-as: ubuntu-latest
    steps:
      - name: menampilkan teks
        run: echo "ini step build"
  testing:
    name: test-apps
    runs-as: ubuntu-latest
    steps:
      - name: menampilkan teks
        run: echo "ini step test"
  deploymant:
    name: deployment-apps
    runs-as: ubuntu-latest
    steps:
      - name: menampilkan teks
        run: echo "ini step deployment"
